spring.application.name=balloon
server.port=8000

spring.datasource.url=jdbc:postgresql://localhost:5432/balloon
spring.datasource.username=postgres
spring.datasource.password=3fc7c6434c596014

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false


jwt.secret=mySecretKey123456789012345678901234567890123456789012345678901234
jwt.expiration=3600000
